# Script to generate Table 1 of the manuscript

# libraries
library(maplet) # omics analysis 
library(tidyverse) # tidy
library(magrittr) # %<>%
library(openxlsx) # excel
library(gtsummary) # table
library(flextable)

# input file
rosmap_met_pdata <- 'results/tmp_rosmap_metabolomics_processed_medcor_data.xlsx'
# outfile
table_outfile <- 'results/table1.docx'

# load preprocessed medication corrected data generated by script 1_*.R
Dmc <- mt_load_xls(file=rosmap_met_pdata, 
                   samples_in_rows = F, is_mt_write_se_xls_output = T)
# turn covariates into factor / numeric
Dmc %<>% mt_anno_mutate(anno_type = "samples", col_name = 'msex', 
                        term = as.factor(msex)) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'apoe_genotype', 
                 term = as.factor(apoe_genotype)) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'pmi', 
                 term = as.numeric(as.matrix(pmi))) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'age_death', 
                 term = as.numeric(as.matrix(age_death))) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'bmi', 
                 term = as.numeric(as.matrix(bmi))) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'educ', 
                 term = as.numeric(as.matrix(educ)))
# demographics Table 1 ----

Y <- Dmc %>% colData() %>% data.frame () %>% 
  select(msex, pmi, bmi, educ, age_death, apoe_genotype, cogdx) %>%
  mutate(msex=case_when(msex==1 ~ 'Male', TRUE~'Female')) %>% 
  mutate(cogdx=case_when(cogdx==1 ~ 'NCI', 
                         cogdx==2 ~ 'MCI', 
                         cogdx==3 ~ 'MCI', 
                         cogdx==4 ~ 'AD',
                         cogdx==5 ~ 'AD',
                         TRUE~ 'Other')) %>% 
  
  dplyr::rename(Gender=msex, PMI=pmi, BMI=bmi, 
                'Years of education'=educ, 
                'Age at death'=age_death, 
                'APOE4 allele'=apoe_genotype,
                'Clinical diagnosis at death' =cogdx)

Y %>% tbl_summary()

Y %>% tbl_summary() %>%
  as_flex_table() %>%
  flextable::save_as_docx(path = table_outfile)

## finished
print("Done! generated Table 1 of the manuscript.") 
print("Generated table1.docx in results folder!") 
