# Script to calculate metabolites associated with demographics factors:
# age, sex, bmi, years of education, post-mortem interval (PMI)

# Generates 2 files with supplementary table 4 (PMI) and  supplementary table 5 (all other factors)


# association analysis cogdx=1

# libraries
library(maplet) # omics analysis 
library(tidyverse) # tidy
library(magrittr) # %<>%
library(glue) # formula
library(openxlsx) # excel
source("internal_functions.R") # customized functions

# input
rosmap_met_pdata <- 'results/tmp_rosmap_metabolomics_processed_medcor_data.xlsx'
# outfile
pmi_outfile <- 'results/supplementary_table_4_metabolic_associations_with_pmi.xlsx'
demo_outfile <- 'results/supplementary_table_5_metabolic_associations_with_covariates_in_controls.xlsx'
# load preprocessed medication corrected data generated by script 1_*.R
Dmc <- mt_load_xls(file=rosmap_met_pdata, 
                   samples_in_rows = F, is_mt_write_se_xls_output = T)
# turn covariates into factor / numeric
Dmc %<>% mt_anno_mutate(anno_type = "samples", col_name = 'msex', 
                        term = as.factor(msex)) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'apoe_genotype', 
                 term = as.factor(apoe_genotype)) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'pmi', 
                 term = as.numeric(as.matrix(pmi))) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'age_death', 
                 term = as.numeric(as.matrix(age_death))) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'bmi', 
                 term = as.numeric(as.matrix(bmi))) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'educ', 
                 term = as.numeric(as.matrix(educ)))

# compute and save metabolic associations ----

# with pmi
pmi_res <- association_analysis(Dmc, outcome = 'pmi', 
                                outcome_type =  'numeric', 
                                conf_formula = 'msex + age_death + bmi + educ + apoe_genotype')


# in cognitively normal samples for the rest of the factors 
D1 <- mt_modify_filter_samples(Dmc, filter=cogdx==1)

# with age at death
age_res <- association_analysis(D1, outcome = 'age_death', 
                                outcome_type =  'numeric', 
                                conf_formula = 'msex + pmi + bmi + educ + apoe_genotype')
# with bmi
bmi_res <- association_analysis(D1, outcome = 'bmi', 
                                outcome_type =  'numeric', 
                                conf_formula = 'msex + age_death + pmi + educ + apoe_genotype')
# with years of education
educ_res <- association_analysis(D1, outcome = 'educ', 
                                outcome_type =  'numeric', 
                                conf_formula = 'msex + pmi + bmi + age_death + apoe_genotype')
# with sex 
sex_res <- association_analysis(D1, outcome = 'msex', 
                                outcome_type =  'twofactor', 
                                conf_formula = 'age_death + pmi + bmi + educ + apoe_genotype')

# write out excel
wb <- openxlsx::createWorkbook()

# age
out <- 'age'; this_res <- age_res %>% .[order(.$adj_p), ] %>%
  select(-analyte) %>% select(name, outcome, covariates, p_value, adj_p, everything())

ws <- openxlsx::addWorksheet(wb,sheetName=sprintf('%s', out))
openxlsx::writeData(wb=wb, sheet=sprintf('%s', out), x=this_res)
# create and add a style to the column headers
headerStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center', textDecoration = 'bold')
# style for body
bodyStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center')
# apply style
addStyle(wb, sheet = sprintf('%s', out), bodyStyle, rows = 1:nrow(this_res), cols = 1:ncol(this_res), gridExpand = TRUE)
addStyle(wb, sheet = sprintf('%s', out), headerStyle, rows = 1, cols = 1:ncol(this_res), gridExpand = TRUE)

# bmi
out <- 'bmi'; this_res <- bmi_res %>% .[order(.$adj_p), ] %>%
  select(-analyte) %>% select(name, outcome, covariates, p_value, adj_p, everything())

ws <- openxlsx::addWorksheet(wb,sheetName=sprintf('%s', out))
openxlsx::writeData(wb=wb, sheet=sprintf('%s', out), x=this_res)
# create and add a style to the column headers
headerStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center', textDecoration = 'bold')
# style for body
bodyStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center')
# apply style
addStyle(wb, sheet = sprintf('%s', out), bodyStyle, rows = 1:nrow(this_res), cols = 1:ncol(this_res), gridExpand = TRUE)
addStyle(wb, sheet = sprintf('%s', out), headerStyle, rows = 1, cols = 1:ncol(this_res), gridExpand = TRUE)

# education
out <- 'educ'; this_res <- educ_res %>% .[order(.$adj_p), ] %>%
  select(-analyte) %>% select(name, outcome, covariates, p_value, adj_p, everything())

ws <- openxlsx::addWorksheet(wb,sheetName=sprintf('%s', out))
openxlsx::writeData(wb=wb, sheet=sprintf('%s', out), x=this_res)
# create and add a style to the column headers
headerStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center', textDecoration = 'bold')
# style for body
bodyStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center')
# apply style
addStyle(wb, sheet = sprintf('%s', out), bodyStyle, rows = 1:nrow(this_res), cols = 1:ncol(this_res), gridExpand = TRUE)
addStyle(wb, sheet = sprintf('%s', out), headerStyle, rows = 1, cols = 1:ncol(this_res), gridExpand = TRUE)

# sex
out <- 'sex'; this_res <- sex_res %>% .[order(.$adj_p), ] %>%
  select(-analyte) %>% select(name, outcome, covariates, p_value, adj_p, everything())

ws <- openxlsx::addWorksheet(wb,sheetName=sprintf('%s', out))
openxlsx::writeData(wb=wb, sheet=sprintf('%s', out), x=this_res)

# create and add a style to the column headers
headerStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center', textDecoration = 'bold')
# style for body
bodyStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center')
# apply style
addStyle(wb, sheet = sprintf('%s', out), bodyStyle, rows = 1:nrow(this_res), cols = 1:ncol(this_res), gridExpand = TRUE)
addStyle(wb, sheet = sprintf('%s', out), headerStyle, rows = 1, cols = 1:ncol(this_res), gridExpand = TRUE)

openxlsx::saveWorkbook(wb, file=demo_outfile, overwrite=T)

# pmi
wb <- openxlsx::createWorkbook()
out <- 'pmi'; this_res <- pmi_res %>% .[order(.$adj_p), ] %>%
  select(-analyte) %>% select(name, outcome, covariates, p_value, adj_p, everything())

ws <- openxlsx::addWorksheet(wb,sheetName=sprintf('%s', out))
openxlsx::writeData(wb=wb, sheet=sprintf('%s', out), x=this_res)
# create and add a style to the column headers
headerStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center', textDecoration = 'bold')
# style for body
bodyStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center')
# apply style
addStyle(wb, sheet = sprintf('%s', out), bodyStyle, rows = 1:nrow(this_res), cols = 1:ncol(this_res), gridExpand = TRUE)
addStyle(wb, sheet = sprintf('%s', out), headerStyle, rows = 1, cols = 1:ncol(this_res), gridExpand = TRUE)

openxlsx::saveWorkbook(wb, file=pmi_outfile, overwrite=T)


## finished
print("Done! ROS/MAP metabolic association analysis demographics factors and PMI completed.") 
print("Generated excel files with supplementary tables 4 and 5 in results folder!") 

