# Script to calculate metabolites with sex and APOE4 dimorphisms in their AD trait associations.

# Generates 2 files for supplementary table 7 and supplementary table 8

# libraries
library(maplet) # omics analysis 
library(tidyverse) # tidy
library(magrittr) # %<>%
library(glue) # formula
library(openxlsx) # excel
library(readxl)
source("internal_functions.R") # customized functions


# input
rosmap_met_pdata <- 'results/tmp_rosmap_metabolomics_processed_medcor_data.xlsx'
file_outcomes <- "input/outcomes.xlsx"# outcomes of interest 
# metabolomics analysis results in overall samples generated by script 4_*.R
overall_res <- 'results/supplementary_table_6_metabolomics_associations_with_ad.xlsx'
# outfiles
sex_strata_outfile <- 'results/supplementary_table_7_sex_stratified_metabolomics_associations.xlsx'
apoe_strata_outfile <- 'results/supplementary_table_8_apeo_stratified_metabolomics_associations.xlsx'
# adjusted pvalue threshold
pcut <- 0.05


# load preprocessed medication corrected data generated by script 1_*.R
Dmc <- mt_load_xls(file=rosmap_met_pdata, 
                   samples_in_rows = F, is_mt_write_se_xls_output = T)
# turn covariates into factor / numeric
Dmc %<>% mt_anno_mutate(anno_type = "samples", col_name = 'msex', 
                        term = as.factor(msex)) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'apoe_genotype', 
                 term = as.factor(apoe_genotype)) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'pmi', 
                 term = as.numeric(as.matrix(pmi))) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'age_death', 
                 term = as.numeric(as.matrix(age_death))) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'bmi', 
                 term = as.numeric(as.matrix(bmi))) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'educ', 
                 term = as.numeric(as.matrix(educ)))
# read outcomes
outcomes <- read.xlsx(file_outcomes)
# untargeted sex beta analysis ----
sex_res <- beta_analysis(D=Dmc, outcomes=outcomes, groups_variable='msex', 
                     group_names=c('females', 'males'), # this variable should match the sequence of levels(as.factor(colData(D)[[groups_variable]]))
                     param_conf_formula=' pmi + age_death + bmi + educ + apoe_genotype')
names(sex_res) <- outcomes$outcome

# untargeted anye4 beta analysis ----
apoe_res <- beta_analysis(D=Dmc, outcomes=outcomes, groups_variable='anye4', 
                     group_names=c('none', 'apoe4'), # this variable should match the sequence of levels(as.factor(colData(D)[[groups_variable]]))
                     param_conf_formula='msex + pmi + age_death + bmi + educ')
names(apoe_res) <- outcomes$outcome

# targeted results
sex_specific <- apoe_specific <- list()
# reading metadata
res <- overall_res %>%
  excel_sheets() %>%
  purrr::set_names() %>%
  map(read_excel, path = overall_res)
# loop over outcomes
sheet_names <- list()
sheet_names[['sqrt_amyloid']] <- 'amyloid (square root)'; sheet_names[['amyloid']] <- 'amyloid'; 
sheet_names[['tangles']] <- 'tangles'; sheet_names[['gpath']] <- 'global np'; 
sheet_names[['niareagansc']] <- 'reagan score'; sheet_names[['diagnosis']] <- 'np diagnosis'; 
sheet_names[['cogdx']] <- 'clinical diagnosis'; 
sheet_names[['cogn_global']] <- 'cognition'; 
sheet_names[['cogng_random_slope']] <- 'cognitive decline'; 
for(outcome in outcomes$outcome){
  this_outcome <- sheet_names[[outcome]]
  this_df <- res[[this_outcome]]
  sex_specific[[outcome]] <- sex_res[[outcome]] %>% 
    dplyr::filter(name %in% (this_df %>% dplyr::filter(adj_p<=pcut) %>%dplyr:: pull(name))) %>%
    dplyr::filter(p_grp<=pcut)
  apoe_specific[[outcome]] <- apoe_res[[outcome]] %>% 
    dplyr::filter(name %in% (this_df %>% dplyr::filter(adj_p<=pcut) %>% dplyr::pull(name))) %>%
    dplyr::filter(p_grp<=pcut)
}

# compute and write out
wb <- openxlsx::createWorkbook()
# loop over outcomes
for(out in outcomes$outcome){
  # compute betas
  this_res <- sex_specific[[out]]
  if(nrow(this_res)>0){
    out <- sheet_names[[out]]
    # create worksheet
    openxlsx::addWorksheet(wb,sprintf('%s', out))
    # write data
    openxlsx::writeData(wb, sprintf('%s', out), this_res ,
                        rowNames = F, colNames = T)
    # create and add a style to the column headers
    headerStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center', textDecoration = 'bold')
    # style for body
    bodyStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center')
    # apply style
    addStyle(wb, sheet = sprintf('%s', out), bodyStyle, rows = 1:nrow(this_res), cols = 1:ncol(this_res), gridExpand = TRUE)
    addStyle(wb, sheet = sprintf('%s', out), headerStyle, rows = 1, cols = 1:ncol(this_res), gridExpand = TRUE)
  }# end if condition for nrow>0
} # end outcome loop

openxlsx::saveWorkbook (wb, file=sex_strata_outfile, overwrite=TRUE)


# compute and write out
wb <- openxlsx::createWorkbook()
for(out in outcomes$outcome){
  # filter results
  this_res <- apoe_specific[[out]]
  if(nrow(this_res)>0){
    out <- sheet_names[[out]]
    # create worksheet
    openxlsx::addWorksheet(wb,sprintf('%s', out))
    # write data
    openxlsx::writeData(wb, sprintf('%s', out), this_res, rowNames = F, colNames = T)
    # create and add a style to the column headers
    headerStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center', textDecoration = 'bold')
    # style for body
    bodyStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center')
    # apply style
    addStyle(wb, sheet = sprintf('%s', out), bodyStyle, rows = 1:nrow(this_res), cols = 1:ncol(this_res), gridExpand = TRUE)
    addStyle(wb, sheet = sprintf('%s', out), headerStyle, rows = 1, cols = 1:ncol(this_res), gridExpand = TRUE)
  }
}
openxlsx::saveWorkbook (wb, file=apoe_strata_outfile, overwrite=TRUE)

## finished
print("Done! ROS/MAP metabolic dimorphism analysis with sex and apoe completed.") 
print("Generated excel files with supplementary tables 7 and 8 in results folder!") 

