# Script to calculate proteins associated with AD traits.

# Generates 2 files for supplementary table 11 and supplementary table 13

# Note: This script is time and resource intensive due to large number of protein imputation steps at line 35
# and the medication correction at line 47 (~18h on a single core)

# libraries
library(maplet) # omics analysis
library(tidyverse) # tidy
library(magrittr) # %<>%
library(glue) # formula
library(openxlsx) # excel
source("internal_functions.R") # customized functions


# input files
proteomics_input <- 'input/proteomics_rosmap.xlsx'
medication_columns <- 'input/medication_columns.xlsx'
file_outcomes <- "input/outcomes.xlsx"
enzymes_file <- 'input/enzymes.xlsx'
rosmap_metadata <- 'input/metadata_rosmap514_brain_ms.xlsx'
# output files
proteomics_output <-
  'results/tmp_rosmap_proteomics_processed_medcor_data.xlsx'
conditional_outfile <-
  'results/supplementary_table_13_proteomics_associations_proteinopathy.xlsx'
enzymes_outfile <-
  'results/supplementary_table_11_targeted_proteomics_association_w_ad.xlsx'

# load preprocessed medication corrected data generated by script 1_*.R
Dp <- mt_load_xls(
  file = proteomics_input,
  samples_in_rows = F,
  is_mt_write_se_xls_output = T
)

# attach metadata
Dp %<>%  mt_anno_xls(file=rosmap_metadata, sheet=1, 
              anno_type = 'samples', anno_id_col = 'projid', data_id_col = 'projid')

# Proteomics preprocessing
Dp %<>% mt_pre_filter_missingness(feat_max = 0.25) %>%
  mt_pre_impute_knn() %>%
  # sample outlier removal
  mt_pre_outlier_lof(seq_k = c(5, 10, 20, 30, 40, 50)) %>%
  # metabolic outlier detection followed by imputation
  mt_pre_outlier_to_na(use_quant = T, quant_thresh = 0.025) %>%
  # kNN imputation
  mt_pre_impute_knn()

# medication correction ----
Dpmc <- Dp %>% # converting all medication columns to factors
  mt_anno_class(anno_type = 'samples',
                file = medication_columns,
                sheet = 1) %>%
  # medication correction
  mt_pre_confounding_correction_stepaic(
    cols_to_correct = names(colData(Dp))[grep("_rx", names(colData(Dp)))],
    cols_to_exclude = c("ad_rx", "neurologic_rx"), n_cores = 1
  )

### delete samples with missing confounders
Dpmc %<>% mt_modify_filter_samples(!is.na(bmi)) %>%
  mt_modify_filter_samples(!is.na(msex)) %>%
  mt_modify_filter_samples(!is.na(educ)) %>%
  mt_modify_filter_samples(!is.na(apoe_genotype)) %>%
  mt_modify_filter_samples(!is.na(age_death)) %>%
  mt_modify_filter_samples(!is.na(pmi)) %>%
  mt_reporting_data()

# turn covariates into factor / numeric
Dpmc %<>% mt_anno_mutate(anno_type = "samples",
                         col_name = 'msex',
                         term = as.factor(msex)) %>%
  mt_anno_mutate(
    anno_type = "samples",
    col_name = 'apoe_genotype',
    term = as.factor(apoe_genotype)
  ) %>%
  mt_anno_mutate(anno_type = "samples",
                 col_name = 'pmi',
                 term = as.numeric(as.matrix(pmi))) %>%
  mt_anno_mutate(anno_type = "samples",
                 col_name = 'age_death',
                 term = as.numeric(as.matrix(age_death))) %>%
  mt_anno_mutate(anno_type = "samples",
                 col_name = 'bmi',
                 term = as.numeric(as.matrix(bmi))) %>%
  mt_anno_mutate(anno_type = "samples",
                 col_name = 'educ',
                 term = as.numeric(as.matrix(educ)))

# compute and save metabolic associations ----
Dpmc %<>% # remove the external suffix from uniprot ids
  mt_anno_mutate(
    anno_type = 'features',
    col_name = 'uniprot',
    term = sub('-..*', '', uniprot)
  ) %>%
  # average out duplicate uniprot ids
  mt_modify_avg_features(group_col = 'uniprot')

mt_write_se_xls(Dpmc, file = proteomics_output)

# load outcomes of interest
outcomes <- read.xlsx(file_outcomes)
# loop association analysis over outcomes
res <- lapply(
  1:nrow(outcomes),
  FUN = function(i) {
    this_res <- association_analysis(
      Dpmc,
      outcome = outcomes$outcome[i],
      outcome_type = outcomes$type[i],
      conf_formula = 'msex + pmi + age_death + bmi + educ + apoe_genotype'
    )
    return(this_res)
  }
) %>% do.call(rbind, .)

# amyloid-tau pathology analysis ----
amy_res <- association_analysis(
  Dpmc,
  outcome = 'sqrt_amyloid',
  outcome_type = 'numeric',
  conf_formula = 'tangles + msex + pmi + age_death + bmi + educ + apoe_genotype'
)

tau_res <- association_analysis(
  Dpmc,
  outcome = 'tangles',
  outcome_type = 'numeric',
  conf_formula = 'sqrt_amyloid + msex + pmi + age_death + bmi + educ + apoe_genotype'
)

# write out
sheet_names <- list()
sheet_names[['sqrt_amyloid']] <-
  'amyloid (square root)'
sheet_names[['amyloid']] <- 'amyloid'

sheet_names[['tangles']] <-
  'tangles'
sheet_names[['gpath']] <- 'global np'

sheet_names[['niareagansc']] <-
  'reagan score'
sheet_names[['diagnosis']] <- 'np diagnosis'

sheet_names[['cogdx']] <- 'clinical diagnosis'

sheet_names[['cogn_global']] <- 'cognition'

sheet_names[['cogng_random_slope']] <- 'cognitive decline'

wb <- openxlsx::createWorkbook()
# loop over outcomes
for (out in outcomes$outcome) {
  # results of this outcome
  this_res <-
    res %>% filter(outcome == out) %>% .[order(.$adj_p),] %>%
    select(-analyte) %>%
    select(name,
           outcome,
           covariates,
           p_value,
           adj_p,
           estimate,
           std_error,
           statistic,
           uniprot)
  # create worksheet
  out <- sheet_names[[out]]
  openxlsx::addWorksheet(wb, sprintf('%s', out))
  # write data
  openxlsx::writeData(wb,
                      sprintf('%s', out),
                      this_res ,
                      rowNames = F,
                      colNames = T)
  # create and add a style to the column headers
  headerStyle <-
    createStyle(
      fontName = 'Arial',
      fontSize = 12,
      halign = 'center',
      valign = 'center',
      textDecoration = 'bold'
    )
  # style for body
  bodyStyle <-
    createStyle(
      fontName = 'Arial',
      fontSize = 12,
      halign = 'center',
      valign = 'center'
    )
  # apply style
  addStyle(
    wb,
    sheet = sprintf('%s', out),
    bodyStyle,
    rows = 1:nrow(this_res),
    cols = 1:ncol(this_res),
    gridExpand = TRUE
  )
  addStyle(
    wb,
    sheet = sprintf('%s', out),
    headerStyle,
    rows = 1,
    cols = 1:ncol(this_res),
    gridExpand = TRUE
  )
}

# abeta pathology
out <-
  'abeta_pathology'
this_res <- amy_res %>% .[order(.$adj_p),] %>%
  select(-analyte) %>% select(name,
                              outcome,
                              covariates,
                              p_value,
                              adj_p,
                              estimate,
                              std_error,
                              statistic,
                              uniprot)
openxlsx::addWorksheet(wb, sprintf('%s', out))
# write data
openxlsx::writeData(wb,
                    sprintf('%s', out),
                    this_res,
                    rowNames = F,
                    colNames = T)
# create and add a style to the column headers
headerStyle <-
  createStyle(
    fontName = 'Arial',
    fontSize = 12,
    halign = 'center',
    valign = 'center',
    textDecoration = 'bold'
  )
# style for body
bodyStyle <-
  createStyle(
    fontName = 'Arial',
    fontSize = 12,
    halign = 'center',
    valign = 'center'
  )
# apply style
addStyle(
  wb,
  sheet = sprintf('%s', out),
  bodyStyle,
  rows = 1:nrow(this_res),
  cols = 1:ncol(this_res),
  gridExpand = TRUE
)
addStyle(
  wb,
  sheet = sprintf('%s', out),
  headerStyle,
  rows = 1,
  cols = 1:ncol(this_res),
  gridExpand = TRUE
)
# tau pathology
out <-
  'tau_pathology'
this_res <- tau_res %>% .[order(.$adj_p),] %>%
  select(-analyte) %>% select(name,
                              outcome,
                              covariates,
                              p_value,
                              adj_p,
                              estimate,
                              std_error,
                              statistic,
                              uniprot)
openxlsx::addWorksheet(wb, sprintf('%s', out))
# write data
openxlsx::writeData(wb,
                    sprintf('%s', out),
                    this_res,
                    rowNames = F,
                    colNames = T)
# create and add a style to the column headers
headerStyle <-
  createStyle(
    fontName = 'Arial',
    fontSize = 12,
    halign = 'center',
    valign = 'center',
    textDecoration = 'bold'
  )
# style for body
bodyStyle <-
  createStyle(
    fontName = 'Arial',
    fontSize = 12,
    halign = 'center',
    valign = 'center'
  )
# apply style
addStyle(
  wb,
  sheet = sprintf('%s', out),
  bodyStyle,
  rows = 1:nrow(this_res),
  cols = 1:ncol(this_res),
  gridExpand = TRUE
)
addStyle(
  wb,
  sheet = sprintf('%s', out),
  headerStyle,
  rows = 1,
  cols = 1:ncol(this_res),
  gridExpand = TRUE
)

openxlsx::saveWorkbook (wb, file = conditional_outfile, overwrite = TRUE)

### targeted proteomics ----
enzymes <- read.xlsx(enzymes_file)
# write out
wb <- openxlsx::createWorkbook()
# loop over outcomes
for (out in outcomes$outcome) {
  # results of this outcome
  this_res <-
    res %>% filter(outcome == out) %>% filter(name %in% enzymes$Symbol) %>%
    mutate(adj_p = p.adjust(p_value, method = 'BH')) %>%
    .[order(.$adj_p),] %>%
    select(-analyte) %>% select(name, outcome, covariates, p_value, adj_p, everything())
  # create worksheet
  out <- sheet_names[[out]]
  openxlsx::addWorksheet(wb, sprintf('%s', out))
  # write data
  openxlsx::writeData(wb,
                      sprintf('%s', out),
                      this_res ,
                      rowNames = F,
                      colNames = T)
  # create and add a style to the column headers
  headerStyle <-
    createStyle(
      fontName = 'Arial',
      fontSize = 12,
      halign = 'center',
      valign = 'center',
      textDecoration = 'bold'
    )
  # style for body
  bodyStyle <-
    createStyle(
      fontName = 'Arial',
      fontSize = 12,
      halign = 'center',
      valign = 'center'
    )
  # apply style
  addStyle(
    wb,
    sheet = sprintf('%s', out),
    bodyStyle,
    rows = 1:nrow(this_res),
    cols = 1:ncol(this_res),
    gridExpand = TRUE
  )
  addStyle(
    wb,
    sheet = sprintf('%s', out),
    headerStyle,
    rows = 1,
    cols = 1:ncol(this_res),
    gridExpand = TRUE
  )
}

openxlsx::saveWorkbook (wb, file = enzymes_outfile, overwrite = TRUE)

## finished
print("Done! ROS/MAP proteomics association analysis with AD-related traits completed.")
print("Generated excel files with supplementary tables 11 and 13 in results folder!")
