# Script to calculate metabolites conditionally associated with amyloid and tangles
# Generates supplementary table 12

# libraries
library(maplet) # omics analysis 
library(tidyverse) # tidy
library(magrittr) # %<>%
library(glue) # formula
library(openxlsx) # excel
source("internal_functions.R") # customized functions

# input
rosmap_met_pdata <- 'results/tmp_rosmap_metabolomics_processed_medcor_data.xlsx'
file_outcomes <- "input/outcomes.xlsx"

# outfiles
conditional_outfile <- 'results/supplementary_table_12_more_metabolomics_associations_proteinopathy.xlsx'

# load preprocessed medication corrected data generated by script 1_*.R
Dmc <- mt_load_se_xls(file=rosmap_met_pdata)
# turn covariates into factor / numeric
Dmc %<>% mt_anno_mutate(anno_type = "samples", col_name = 'msex', 
                        term = as.factor(msex)) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'apoe_genotype', 
                 term = as.factor(apoe_genotype)) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'pmi', 
                 term = as.numeric(as.matrix(pmi))) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'age_death', 
                 term = as.numeric(as.matrix(age_death))) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'bmi', 
                 term = as.numeric(as.matrix(bmi))) %>%
  mt_anno_mutate(anno_type = "samples", col_name = 'educ', 
                 term = as.numeric(as.matrix(educ)))

# compute and save metabolic associations ----
# new SE with reduced rowData
D1 <- SummarizedExperiment(assays = assay(Dmc) %>% data.frame(), 
                           rowData = rowData(Dmc) %>% data.frame() %>% dplyr::rename(HMDB=ID) %>%
                             select(name, SUB_PATHWAY, SUPER_PATHWAY, HMDB, PUBCHEM, CAS, KEGG, COMP_ID),
                           colData= colData(Dmc) %>% data.frame(),
                           metadata = list())

# standard association analysis
outcomes <- read.xlsx(file_outcomes)

# conditional analysis
# for amyloid
amy_res <- association_analysis(D1, 
                                outcome = 'sqrt_amyloid', 
                                outcome_type = 'numeric', 
                                conf_formula = 'tangles + msex + pmi + age_death + bmi + educ + apoe_genotype')
# for tau
tau_res <- association_analysis(D1, 
                                outcome = 'tangles', 
                                outcome_type = 'numeric', 
                                conf_formula = 'sqrt_amyloid + msex + pmi + age_death + bmi + educ + apoe_genotype')


# write out conditional restuls
wb <- openxlsx::createWorkbook()
# abeta pathology
out <- 'abeta_pathology'; this_res <- amy_res %>% .[order(.$adj_p), ] %>%
  select(-analyte) %>% select(name, outcome, covariates, p_value, adj_p, everything())
openxlsx::addWorksheet(wb,sprintf('%s', out))
# write data
openxlsx::writeData(wb, sprintf('%s', out), this_res, rowNames = F, colNames = T)
# create and add a style to the column headers
headerStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center', textDecoration = 'bold')
# style for body
bodyStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center')
# apply style
addStyle(wb, sheet = sprintf('%s', out), bodyStyle, rows = 1:nrow(this_res), cols = 1:ncol(this_res), gridExpand = TRUE)
addStyle(wb, sheet = sprintf('%s', out), headerStyle, rows = 1, cols = 1:ncol(this_res), gridExpand = TRUE)
# tau pathology
out <- 'tau_pathology'; this_res <- tau_res %>% .[order(.$adj_p), ] %>%
  select(-analyte) %>% select(name, outcome, covariates, p_value, adj_p, everything())
openxlsx::addWorksheet(wb,sprintf('%s', out))
# write data
openxlsx::writeData(wb, sprintf('%s', out), this_res, rowNames = F, colNames = T)
# create and add a style to the column headers
headerStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center', textDecoration = 'bold')
# style for body
bodyStyle <- createStyle(fontName = 'Arial', fontSize = 12, halign = 'center', valign = 'center')
# apply style
addStyle(wb, sheet = sprintf('%s', out), bodyStyle, rows = 1:nrow(this_res), cols = 1:ncol(this_res), gridExpand = TRUE)
addStyle(wb, sheet = sprintf('%s', out), headerStyle, rows = 1, cols = 1:ncol(this_res), gridExpand = TRUE)

# write workbook
openxlsx::saveWorkbook (wb, file=conditional_outfile, overwrite=TRUE)

## finished
print("Done! ROS/MAP metabolomics conditional analysis with amyloid and tau completed.") 
print("Generated excel files with supplementary table 12  in results folder!") 
