# Figures 2, 3, 4

# Note: Cytoscape needs to be running and allow incoming connections to
# generate GGM networks (see also RCy3 package).
# set the flag to F at line 44 to skip cytoscape part of the script
# once the networks are printed in cytoscape we remove self-loops: Edit --> "remove self-loops"
# and then save it using File --> save as --> 'supplementary_file1_ggm_with_metabolomics_associations_with_ad.cys'


# libraries
library(maplet) # omics analysis
library(readxl) # reading excel with multiple sheets
library(tidyverse) # tidy
library(magrittr) # tidy+
library(SummarizedExperiment)
library(openxlsx) # excel
library(gtsummary) # table
library(ggplot2)
library(UpSetR) # upset
library(eulerr) # venn diagram
library(pheatmap) # heatmaps
library(RColorBrewer) # color palettes
library(colorspace)
library(GeneNet) # ggm
library(RCy3) # cytoscape
library(igraph) # igraph


# input file names ----
# output of script 1_*.R
rosmap_met_pdata <- 'results/tmp_rosmap_metabolomics_processed_medcor_data.xlsx'
# output of script 4_*.R
rosmap_results <- 'results/supplementary_table_6_metabolomics_associations_with_ad.xlsx'
# output of script 4_*.R
metabolomics_conditional_results <- 'results/supplementary_table_9_metabolomics_associations_proteinopathy.xlsx'
# output of script 7_*.R
rosmap_proteomics_results <- 'results/supplementary_table_10_proteomics_associations_proteinopathy.xlsx'
# output of script 6_*.R
mayo_results <- 'results/supplementary_table_11_mayo_ad_tcx_metabolomics_associations.xlsx'
blsa_results <- 'input/blsa_results.xlsx'
file_outcomes <- "input/outcomes.xlsx"


# define parameters and colors ----
# plot networks in cytoscape?
to_cytoscape <- T
# adjusted p-value cutoff
pcut <- 0.05
# for super-pathways
annocols <- brewer.pal(n = 9, name = "Pastel1")
# for multiple figures
# for heatmap inside numbers
grey <- brewer.pal(n = 9, name = "Greys")
shadesOfGrey <- colorRampPalette(c("grey0", "grey100"))
# white to grey # for boxplots
my_greys <- c('#FFFFFF', rev(shadesOfGrey(100)[-c(1:64, 93:100)]))
# for heatmaps
my_greys2 <- c(my_greys[seq(1, 29, by=2)], rev(shadesOfGrey(100)[51:80])[c(17, 18, 20, 22, 24, 26, 28, 30)])
# for replication
my_cols <- c('#A2D9CE', '#2980B9', '#AED6F1', '#AEB6BF')

# load preprocessed medication corrected data generated by script 1_*.R
D <- mt_load_xls(file=rosmap_met_pdata, 
                 samples_in_rows = F, is_mt_write_se_xls_output = T)

# reading rosmap results
res <- rosmap_results %>%
  excel_sheets() %>%
  purrr::set_names() %>%
  map(read_excel, path = rosmap_results) %>%
  purrr::imap(~mutate(.x, group = .y)) %>% bind_rows()

#### format rosmap association results
met_stats <- 
  res %>% 
  # change the direction of statistics so all phenotypes are in same direction w AD incidence
  dplyr::mutate(statistic = case_when((outcome == "cogn_global" | outcome=='cogng_random_slope') 
                                      ~ -1*statistic, TRUE ~ statistic), 
                # create a variable for sign of association
                stat_sign = case_when(statistic > 0 ~ 1, statistic < 0 ~ -1), 
                # create the log pvalue score
                pval_score = ((-1*(log10(adj_p))) * stat_sign)) %>%  
  # selected columns for the rest of the analysis
  dplyr::select(name, outcome, SUB_PATHWAY, SUPER_PATHWAY, adj_p, stat_sign, pval_score, COMP_ID) %>% 
  # rename term to phenotype
  dplyr::rename(Phenotype=outcome) %>%
  
  # formal names of phenotypes
  dplyr::mutate(Phenotype= case_when(Phenotype=='cogng_random_slope' ~ "Cognitive Decline",
                                     Phenotype=='cogn_global' ~ "Cognition",
                                     Phenotype=='cogdx' ~ "Clinical Diagnosis",
                                     Phenotype=='niareagansc' ~ "Reagan Score", 
                                     Phenotype=='tangles' ~ 'Tangles', 
                                     Phenotype=='amyloid' ~ 'Amyloid_orig', 
                                     Phenotype=='gpath' ~ 'Global NP',
                                     Phenotype=='diagnosis' ~ 'NP Diagnosis', 
                                     Phenotype=='sqrt_amyloid' ~ 'Amyloid'),
                SUPER_PATHWAY=
                  case_when(is.na(SUPER_PATHWAY) ~ 'Unknowns', TRUE~SUPER_PATHWAY),
                SUB_PATHWAY=
                  case_when(is.na(SUB_PATHWAY) ~ 'Unknowns', TRUE~SUB_PATHWAY)) %>% unique()


# Figure 2a ----
# distribution of metabolic classes
pie_stats <- # row data to get metabolites and their annotations
  D %>% rowData()%>% data.frame() %>% 
  select(name, SUB_PATHWAY, SUPER_PATHWAY) %>% 
  # rename the ones without annotations to other
  mutate(SUPER_PATHWAY = case_when(is.na(SUPER_PATHWAY)~'Unknowns', TRUE~SUPER_PATHWAY)) %>% 
  # format the data frame
  unique() %>% select(SUPER_PATHWAY) %>% table() %>% reshape2::melt(.) %>% 
  dplyr::rename(Class= '.') %>%
  # compute proportions
  mutate(prop = round(100*(value / sum(value)), 2),      
         cumulative = cumsum(value),
         midpoint = cumulative - value / 2, 
         label = paste0(Class, " ", round(value / sum(value) * 100, 1), "%"))

# factor levels need to be the opposite order of the cumulative sum of the values
pie_stats$Class <- factor(pie_stats$Class, levels=rev(pie_stats$Class))
# plot
pdf(file='results/Figure2a_ROSMAP_met_pie.pdf', width=5, height=5)
plot(
  ggplot(pie_stats, aes(x = 1, weight = value, fill = Class)) +
    geom_bar(width = 1, position = "stack", size=1.3, color='#FDFEFE') +
    coord_polar(theta = "y") +
    geom_text(aes(x = 1.3, y = midpoint, label = label), size=6) +
    theme_void() + theme(text = element_text(size=15))+ 
    scale_fill_manual(values=rev(annocols))+ theme(legend.position ='none') 
)
dev.off()


# Figure 2b ---- 
# phenotype corrplot
# get the coldata from SE
Y <-  D %>% colData() %>% data.frame() %>% 
  # select relevant columns
  select(sqrt_amyloid, tangles, gpath, niareagansc, 
         diagnosis, cogdx, cogn_global, cogng_random_slope)
# kendall correlation
cor_mat <- cor(Y, method = 'kendall', use='pairwise')
rownames(cor_mat) <- colnames(cor_mat) <- c('Amyloid', 'Tangles',  
                                            'Global NP', 'Reagan Score', 
                                            'NP Diagnosis', 
                                            'Clinical Diagnosis', 
                                            'Cognition', 
                                            'Cognitive Decline')
# corrplot
pdf('results/Figure2b_rosmap_phenotype_corplot.pdf', useDingbats = F)
corrplot::corrplot(cor_mat, type='lower', col=colorRampPalette(c('#3498DB', '#FDFEFE', '#E74C3C'))(200))
dev.off()


#### overlap in associations of different phenotypes
plot_mat <- met_stats %>% 
  # remove the untransformed amyloid results
  filter(adj_p<=pcut & Phenotype!="Amyloid_orig") %>% 
  # select relevant columns
  select(name, Phenotype)
# coount frequencies in each annotation group
plot_mat %<>% left_join(plot_mat %>% dplyr::group_by(name) %>% 
                          dplyr::count(), by='name')%>% dplyr::rename(met_n=n)
plot_mat %<>% left_join(plot_mat %>% dplyr::group_by(Phenotype) %>% 
                          dplyr::count(), by='Phenotype')%>% dplyr::rename(Pheno_n=n)

# Figure 2c ----
# simple bar plot associations per phenotype
tmp <- plot_mat %>% select(Phenotype, Pheno_n) %>% unique()
tmp$Phenotype <- factor(tmp$Phenotype, levels=rev(c('Amyloid', 'Tangles', 'Global NP', 'Reagan Score', 'NP Diagnosis', 'Clinical Diagnosis', 'Cognition', 'Cognitive Decline')))
pdf(file='results/Figure2c_ROSMAP_Pheno_Simple_Barplot.pdf', width=10, height=6)
plot(
  ggplot(tmp, aes(y=Pheno_n, x=Phenotype, fill=Phenotype, label=Pheno_n)) + 
    geom_bar(stat="identity") +
    geom_text(size = 5)+
    ylab("#significant associations") + 
    xlab("#phenotypes") + 
    theme_classic() + 
    theme(text = element_text(size=15))+
    ggtitle ("Distribution of sig asso. across phenotypes") +
    scale_fill_manual(values=rep(c('#D9D9D9'), 8))+
    coord_flip(clip = 'off') + theme(legend.position = 'none')
)
dev.off()

# supplementary figure ----
pheno_list <- lapply(unique(plot_mat$Phenotype), FUN=function(x)plot_mat$name[which(plot_mat$Phenotype%in%x)])
names(pheno_list) <- unique(plot_mat$Phenotype)
pdf(file='results/SFigure1_ROSMAP_associations_upset.pdf', width=10, height=6, useDingbats = F)
print(upset(fromList(pheno_list), nsets = 9, nintersects = NA))
dev.off()


# Figure 2d ----
X <- assay(D)
# left plot
# cognitive decline
y <- D$cogng_random_slope
# median for splitting data into two
med_y <- median(y, na.rm=T)
y[which(D$cogng_random_slope <= med_y)] <- sprintf('>%g', med_y) # inverse for this phenotype
y[which(D$cogng_random_slope > med_y)] <- sprintf('<%g', med_y) # inverse for this phenotype
# format for plotting with selected metabolite
plot_mat <- reshape2::melt(split(X[which(rowData(D)$name%in%'glycerophosphoethanolamine'), ], y))
# plot
p1 <- ggplot(plot_mat, aes(x=L1, y=value, fill=L1))+
  geom_boxplot () + geom_jitter(alpha=0.4, size=0.8) + 
  theme_bw() +
  scale_fill_manual(values=c(my_greys[4], '#9A9A9A'), name='')+
  xlab('Cognitive Decline') + ylab('Glycerophosphoethanolamine abundance')+ 
  ggtitle('') + theme(legend.position = 'none') + 
  theme(text = element_text(size=12))

# right plot
# global burden of AD neuropathology
y <- D$gpath
# median for splitting data into two
med_y <- median(y, na.rm=T)
y[which(D$gpath <= med_y)] <- sprintf('<%g', med_y)
y[which(D$gpath > med_y)] <- sprintf('>%g', med_y)
# format for plotting with selected metabolite
plot_mat <- reshape2::melt(split(X[which(rowData(D)$name%in%'N-acetylglutamate'), ], y))
# plot
p2<- ggplot(plot_mat, aes(x=L1, y=value, fill=L1))+
  geom_boxplot () + geom_jitter(alpha=0.4, size=0.8) + 
  theme_bw() +
  scale_fill_manual(values=c(my_greys[4], '#9A9A9A'), name='')+
  xlab('Global NP') + ylab('N-acetylglutamate abundance')+ 
  ggtitle('') + theme(legend.position = 'none') +
  theme(text = element_text(size=12))
# saving plots in pdf
pdf(file='results/Figure2d_ROSMAP_example_Boxplots.pdf', width=4, height=4)
plot(p1)
plot(p2)
dev.off()

#### rosmap pathway heatmaps
path_stats <- met_stats %>% 
  # select only significant metabolites
  filter(adj_p<=pcut & Phenotype!='Amyloid_orig') %>% 
  # select relevant columns
  select(Phenotype, SUB_PATHWAY, SUPER_PATHWAY) %>%
  # turn na pathways to Unknown
  mutate(SUPER_PATHWAY=
           case_when(is.na(SUPER_PATHWAY) ~ 'Unknowns', TRUE~SUPER_PATHWAY),
         SUB_PATHWAY=
           case_when(is.na(SUB_PATHWAY) ~ 'Unknowns', TRUE~SUB_PATHWAY), 
         # create subpathway+ phenotype id
         uid=paste(Phenotype, SUB_PATHWAY, sep='-'), 
         supid=paste(Phenotype, SUPER_PATHWAY, sep='-')) %>% 
  {.}
#filter(SUB_PATHWAY!='Unknown')

## heatmap with subpathways
# count the number of subpathways per phenotype
subpath_stats <- path_stats %>% group_by(uid) %>% dplyr::count() %>%  ungroup() %>% 
  select(uid, n) %>% 
  left_join(., path_stats, by='uid') %>% 
  unique() %>% select(Phenotype, SUB_PATHWAY, n) %>% 
  spread(Phenotype, n)

# annotations of subpathway - superpathways they belong to
annot_mat <- left_join(subpath_stats %>% select(SUB_PATHWAY), 
                       path_stats %>% select(SUB_PATHWAY, SUPER_PATHWAY), 
                       by='SUB_PATHWAY') %>% unique() %>% select(SUPER_PATHWAY) %>%
  dplyr::rename(SUP=SUPER_PATHWAY) %>% data.frame()
# name vector to be used later in pheatmap
row_names <- subpath_stats$SUB_PATHWAY
subpath_stats <- # select the phenotype columns
  subpath_stats %>% select(-SUB_PATHWAY) %>% 
  # replace nas with zero
  mutate_all(~replace(., is.na(.), 0)) %>% 
  # reorder columns
  select (all_of(c('Amyloid','Tangles', 'Global NP', 
                   'Reagan Score', 'NP Diagnosis', 'Clinical Diagnosis', 
                   'Cognition', 'Cognitive Decline')))

# order the data according to the super pathways
tmp_data <- bind_cols(annot_mat, SUB=row_names, subpath_stats)
tmp_data <- tmp_data[order(tmp_data$SUP, tmp_data$SUB), ]
#tmp_data %<>% filter(SUB!='Unknown')
annot_mat <- tmp_data %>% select(SUP)
# color list of annotations i.e super pathways
annocols_list <- annocols # [-length(annocols)]# defined above pastel colors
names(annocols_list) <- unique(annot_mat$SUP)
annocols_list <- list(SUP=annocols_list)
row_names <- tmp_data$SUB
plot_mat <- tmp_data %>% select(-c(SUP, SUB))

## last column in subpathway heatmap
tmp <- met_stats %>% filter(adj_p<=pcut) %>% 
  select(name, SUB_PATHWAY) %>% unique() %>% 
  pull(SUB_PATHWAY) %>% table() %>% sort() %>% 
  reshape2::melt() %>% dplyr::rename(SUB_PATHWAY='.') %>% 
  left_join(reshape2::melt(table(rowData(D)$SUB_PATHWAY)), by=c("SUB_PATHWAY"="Var1")) %>%
  filter(!is.na(SUB_PATHWAY)) %>% 
  mutate(prop = value.x/value.y)
# add it to the heatmap matrix
plot_mat %<>% mutate(Overall = tmp$value.x[match(row_names, tmp$SUB_PATHWAY)])
rownames(annot_mat) <- rownames(plot_mat) <- row_names

# supplementary figure
pdf(file='results/SFigure2_ROSMAP_Subpathway_heatmap.pdf', height=22, width=8.5)
pheatmap(plot_mat, cluster_rows = F, 
         cluster_cols = F, angle_col = 45, cellwidth = 13, 
         cellheight = 13, display_numbers = 'T', 
         number_format = '%g', 
         labels_row = row_names, 
         gaps_row = c(14, 22, 29, 30, 65, 72, 74, 75), 
         gaps_col = c(2, 5, 8),
         color=my_greys, annotation_row = annot_mat, 
         annotation_colors = annocols_list,
         number_color = grey[9], 
         breaks = seq(0, 14, by = 0.5))
dev.off()

## heatmap with superpathways
# count the number of superpathways per phenotype
suppath_stats <- path_stats %>% group_by(supid) %>% dplyr::count() %>%  ungroup() %>% 
  select(supid, n) %>% 
  left_join(., path_stats, by='supid') %>% 
  unique() %>% select(Phenotype, SUPER_PATHWAY, n) %>% unique() %>%
  spread(Phenotype, n)

# name vector to be used later in pheatmap
row_names <- suppath_stats$SUPER_PATHWAY
suppath_stats <- # select the phenotype columns
  suppath_stats %>% select(-SUPER_PATHWAY) %>% 
  # replace nas with zero
  mutate_all(~replace(., is.na(.), 0)) %>% 
  # reorder columns
  select (all_of(c('Amyloid','Tangles', 'Global NP', 
                   'Reagan Score', 'NP Diagnosis', 'Clinical Diagnosis', 
                   'Cognition', 'Cognitive Decline')))

## last column in superpathway heatmap
tmp <- met_stats %>% filter(adj_p<=pcut) %>% 
  select(name, SUPER_PATHWAY) %>% unique() %>% 
  pull(SUPER_PATHWAY) %>% table() %>% sort() %>% 
  reshape2::melt() %>% dplyr::rename(SUPER_PATHWAY='.') %>% 
  left_join(reshape2::melt(table(rowData(D)$SUPER_PATHWAY)), by=c("SUPER_PATHWAY"="Var1")) %>%
  filter(!is.na(SUPER_PATHWAY)) %>% 
  mutate(prop = value.x/value.y)
# add it to the heatmap matrix
suppath_stats %<>% mutate(Overall = tmp$value.x[match(row_names, tmp$SUPER_PATHWAY)])

# Figure 2e ----
pdf(file='results/Figure2e_ROSMAP_Superpathway_heatmap.pdf', width=5, height=6)
pheatmap(suppath_stats, cluster_rows = F, 
         cluster_cols = F, angle_col = 45, cellwidth = 15, 
         cellheight = 10, display_numbers = 'T', 
         number_format = '%g', 
         labels_row = row_names, 
         gaps_row = c(1, 2, 3, 4, 5, 6, 7, 8), 
         gaps_col = c(2, 5, 8),
         color= my_greys2,
         number_color = grey[9], 
         breaks = c(0:10, 15, 20, 25, seq(30, 110, by=10)))
dev.off()


# GGM generation ----
if(to_cytoscape){
  outcome_names <- list()
  outcome_names[['sqrt_amyloid']] <-
    'amyloid (square root)'
  outcome_names[['amyloid']] <- 'amyloid'
  
  outcome_names[['tangles']] <-
    'tangles'
  outcome_names[['gpath']] <- 'global np'
  
  outcome_names[['niareagansc']] <-
    'reagan score'
  outcome_names[['diagnosis']] <- 'np diagnosis'
  
  outcome_names[['cogdx']] <- 'clinical diagnosis'
  
  outcome_names[['cogn_global']] <- 'cognition'
  
  outcome_names[['cogng_random_slope']] <- 'cognitive decline'
  
  # loop over phenotypes
  outcomes <- read.xlsx(file_outcomes) %>% filter(!outcome=='amyloid')
  cytoscape_data <- lapply(1:nrow(outcomes), FUN=function(i) {
    this_df <- res %>% filter(outcome%in%outcomes$outcome[i]) %>%
      # change the direction of statistics so all phenotypes are in same direction w AD incidence
      dplyr::mutate(statistic = case_when((outcome == "cogn_global" | outcome=='cogng_random_slope') 
                                          ~ -1*statistic, TRUE ~ statistic))
                    
    # select relevant columns
    y <- this_df %>% select(adj_p, statistic)
    # add more relevant columns
    y %<>% mutate(phenotype = outcomes$outcome[i], 
                  stat_sign = case_when(statistic > 0 ~ 1, statistic < 0 ~ -1), 
                  pval_score = (-1 * log10(adj_p)) * stat_sign)
    # add the name of phenotype in the columns
    names(y) <- paste0(outcomes$outcome[i], '_', names(y))
    # add metabolite names
    y <- bind_cols(this_df %>% select(name), y)
    return(y)
  }) %>% plyr::join_all(by=c('name'), type='left') # stich all phenotypes together
  
  # to find super score max of abs valute with direction
  get_super_score <- function(...){
    a <- tibble(...) %>% unlist()
    a[which(abs(a)==max(abs(a)))]
  }
  # add pathway annotations and super score
  cytoscape_data %<>% left_join(rowData(D) %>% data.frame() %>% 
                                  select(name, SUB_PATHWAY, SUPER_PATHWAY), by=c('name'='name')) %>%
    mutate(SUB_PATHWAY=case_when(is.na(SUB_PATHWAY)~'Unknown', TRUE~SUB_PATHWAY),
           super_score = cytoscape_data %>% .[, grepl('pval_score', names(cytoscape_data))] %>% 
             as.tibble() %>% pmap_dbl(get_super_score))
  
  # computation of ggm
  this_mat <- D %>% assay () %>% t () %>% data.frame()
  colnames(this_mat) <- D %>% rowData() %>% data.frame() %>% pull(name)
  pcor_mat <- ggm.estimate.pcor(as.matrix(this_mat), method = "dynamic", verbose = F)
  pval_mat <- network.test.edges(pcor_mat, plot = F, verbose = F)
  pval_mat$p.adj.bh <- p.adjust(pval_mat$pval, method="BH")
  pval_mat$p.adj.bon <- p.adjust(pval_mat$pval, method="bonferroni")
  
  # transform the pcor mat into edge list
  # igraph object
  tmp <- pcor_mat %>% graph_from_adjacency_matrix(mode='undirected', weighted = T) %>% 
    igraph::simplify() # remove self edges
  # igraph to data frame
  ggm_edges <- cbind.data.frame(get.edgelist(tmp), edge_attr(tmp)$weight)
  names(ggm_edges) <- c("source", "target", "pcor_val")
  # add edge_type based on sign of pcor
  ggm_edges %<>% mutate(edge_type = case_when(pcor_val > 0 ~ "pos", pcor_val < 0 ~ "neg"))%>%
    data.frame(.,stringsAsFactors=FALSE)
  
  #### edge list
  # edge pvalue threshold ; # name of edge pvalue correction
  ggm_thresh <- 0.05 ; method_name <- 'GGM_Bon'
  
  # select only significant edges
  ggm_edges %<>% filter(abs(pcor_val)>=min(abs(pval_mat$pcor[pval_mat$p.adj.bon<=ggm_thresh])))
  
  # all nodes possible in the network
  all_nodes <- D %>% rowData() %>% data.frame() %>% pull(name)
  # nodes with at least one edge
  con_nodes <- c(as.matrix(ggm_edges%>% pull(source)), as.matrix(ggm_edges%>% pull(target)))
  # nodes with no edge
  island_nodes <- setdiff(all_nodes, con_nodes)
  # island edges with the node itself
  island_edges <- data.frame(source=island_nodes, target=island_nodes, pcor_val=1) 
  # add nodes with no sig edge to edge list?
  ggm_edges <- bind_rows(ggm_edges, island_edges)
  
  # nodes
  # build a node attribute data frame from edge list
  node_attributes <- data.frame(node_name=unique(c(as.matrix(ggm_edges$source), as.matrix(ggm_edges$target))), 
                                node_type="Metabolite") %>% 
    # add node statistics
    left_join(cytoscape_data, by=c("node_name"= "name"))
  # add numeric ids of the nodes
  node_attributes %<>% mutate(id=as.character(1:nrow(node_attributes)))
  # add numeric equivalent of edges
  ggm_edges <- node_attributes %>% dplyr::select(id, node_name) %>% 
    left_join(ggm_edges,.,by=c("source"= "node_name")) %>% dplyr::rename(from=source, source=id)
  ggm_edges <- node_attributes %>% dplyr::select(id, node_name) %>% 
    left_join(ggm_edges,.,by=c("target"= "node_name")) %>% dplyr::rename(to=target, target=id)
  # formating of dataframes for cytoscape
  ggm_edges <- data.frame(ggm_edges, stringsAsFactors=FALSE)
  node_attributes <- data.frame(node_attributes, row.names = node_attributes$id, stringsAsFactors = F)
  
  
  # Figure 2f and supplementary file ----
  
  # name of network collection
  this_collection <- "ROS/MAP (GGM, FWER 5%)"
  
  # loop over outcome
  for (outcome_name in outcomes$outcome){
    this_style <- this_net <- outcome_names[[outcome_name]]
    # load the network to cytoscape
    RCy3::createNetworkFromDataFrames(edges=ggm_edges[,c('source', 'target')], title=this_net, collection=this_collection)
    # workaround for a bug
    ggm_edges <- ggm_edges %>% mutate(key=paste(source, "(interacts with)", target))
    
    # get SUID for edges and match with edge attributes
    cy_edges <- getTableColumns(table = 'edge')
    cy_edges <- cy_edges[order(cy_edges$name), ]
    ggm_edges <- ggm_edges[order(ggm_edges$key), ]
    ggm_edges$cpSUID <- cy_edges$SUID
    
    # add edge attributes
    loadTableData(subset(ggm_edges, select = -c(source, target)),
                  data.key.column = 'cpSUID', table.key.column = 'SUID',
                  table = 'edge')
    
    # add node attributes
    loadTableData(node_attributes, data.key.column = 'id', table = 'node')
    #then prepare style variables
    style.name = this_style
    nodeLabels <- RCy3::mapVisualProperty('node label','node_name','p')
    edgeStyles <- RCy3::mapVisualProperty('edge line type', 'edge_type', 'd',
                                          c("neg", "pos"), c("LONG_DASH", "SOLID"))
    #and then create the style
    RCy3::createVisualStyle(style.name=style.name, base.url = 'http://localhost:1234/v1',
                            mappings = list(nodeLabels, edgeStyles))
    
    #finish by applying the style
    RCy3::setVisualStyle(style.name=style.name, base.url = 'http://localhost:1234/v1',
                         network = this_net)
    # coloring nodes based on this phenotype
    max_val <- max(abs(node_attributes[[(sprintf('%s_pval_score', make.names(outcome_name)))]]), na.rm=T)
    RCy3::setNodeColorMapping(
      table.column = as.name(sprintf('%s_pval_score', make.names(outcome_name))),
      table.column.values = c(-1*max_val, 0, max_val),
      mapping.type = "c",
      colors= c('#E74C3C' ,'#F0F3F4', '#3498DB'),
      style.name=style.name, base.url = 'http://localhost:1234/v1',
      network = this_net
    )
    # setting the layout
    RCy3::layoutNetwork(layout.name = 'cose', network = this_net, base.url = 'http://localhost:1234/v1')
  } # closing the outcome names
  
  # print with super outcome
  this_style <- this_net <- 'min_adj_pval_across_traits'
  # load the network to cytoscape
  RCy3::createNetworkFromDataFrames(edges=ggm_edges[,c('source', 'target')], title=this_net, collection=this_collection)
  # workaround for a bug in cytoscape
  ggm_edges <- ggm_edges %>% mutate(key=paste(source, "(interacts with)", target))
  # get SUID for edges and match with edge attributes
  cy_edges <- getTableColumns(table = 'edge')
  cy_edges <- cy_edges[order(cy_edges$name), ]
  ggm_edges <- ggm_edges[order(ggm_edges$key), ]
  ggm_edges$cpSUID <- cy_edges$SUID
  # add edge attributes
  RCy3::loadTableData(subset(ggm_edges, select = -c(source, target)),
                      data.key.column = 'cpSUID', table.key.column = 'SUID',
                      table = 'edge')
  # add node attributes
  RCy3::loadTableData(node_attributes, data.key.column = 'id', table = 'node')
  #then prepare style variables
  style.name = this_style
  nodeLabels <- RCy3::mapVisualProperty('node label','node_name','p')
  edgeStyles <- RCy3::mapVisualProperty('edge line type', 'edge_type', 'd',
                                        c("neg", "pos"), c("LONG_DASH", "SOLID"))
  # and then create the style
  RCy3::createVisualStyle(style.name=style.name, base.url = 'http://localhost:1234/v1',
                          mappings = list(nodeLabels, edgeStyles))
  # finish by applying the style
  RCy3::setVisualStyle(style.name=style.name, base.url = 'http://localhost:1234/v1',
                       network = this_net)
  # coloring nodes based on superscore
  max_val <- max(abs(node_attributes$super_score), na.rm=T)
  RCy3::setNodeColorMapping(
    table.column = 'super_score',
    table.column.values = c(-1*max_val, 0, max_val),
    mapping.type = "c",
    colors= c('#E74C3C' ,'#F0F3F4', '#3498DB'),
    style.name=style.name, base.url = 'http://localhost:1234/v1',
    network = this_net
  )
  # setting the layout
  RCy3::layoutNetwork(layout.name = 'cose', network = this_net, base.url = 'http://localhost:1234/v1')
}
# Figure 3: Conditional analysis ----


# ...metabolomics ----
# load conditional analysis results of metabolomics
amy_res <- read.xlsx(metabolomics_conditional_results, sheet='abeta_pathology')
tau_res <- read.xlsx(metabolomics_conditional_results, sheet='tau_pathology')
# results of conditional and standard analysis
res_list <- list()
res_list[['Amyloid*']] <- amy_res %>% filter(adj_p  <=pcut) %>% pull(name)
res_list[['Tangles*']] <- tau_res %>% filter(adj_p  <=pcut) %>% pull(name)
res_list[['Amyloid']] <- res %>% filter(adj_p<=pcut & outcome=='sqrt_amyloid') %>% pull(name)
res_list[['Tangles']] <- res %>% filter(adj_p<=pcut & outcome=='tangles') %>% pull(name)
# results list for stacked barplot
tmp <- list()
tmp[['only_st']] <- setdiff(res_list$Tangles, res_list$`Tangles*`) %>% length()
tmp[['only_ct']] <- setdiff(res_list$`Tangles*`, res_list$Tangles) %>% length()
tmp[['both_t']] <- intersect(res_list$Tangles, res_list$`Tangles*`) %>% length()
tmp[['only_sa']] <- setdiff(res_list$Amyloid, res_list$`Amyloid*`) %>% length()
tmp[['only_ca']] <- setdiff(res_list$`Amyloid*`, res_list$Amyloid) %>% length()
tmp[['both_a']] <- intersect(res_list$Amyloid, res_list$`Amyloid*`) %>% length()

# format the data
tmp2 <- reshape2::melt(tmp)
tmp2$np <- c('t', 't', 't', 'a', 'a', 'a')
tmp2$L1 <- factor(tmp2$L1, levels=c('only_st', 'only_ct', 'both_t', 'only_sa', 'only_ca','both_a'))
# stacked batplot
p1 <- ggplot(tmp2, aes(x=np, y=value, fill=L1, label=value)) +
  geom_bar(stat="identity", position = 'stack') +
  geom_text(size = 3, position = position_stack(vjust = 0.5))+
  xlab("") + ylab("") + theme_classic() +
  theme(text = element_text(size=15)) + ggtitle ("") +
  scale_fill_manual(values=c('#117A65', '#45B39D', '#73C6B6', '#D4AC0D', '#F7DC6F', '#F9E79F' ), name='Significance')+
  coord_flip(clip = 'off')
# plot
pdf('results/Figure3a_metabolomics_proteinopathy_barplot.pdf', height = 2, width=6)
plot(p1)
dev.off()


# ...proteomics ----
# load proteomics results
res <- rosmap_proteomics_results %>%
  excel_sheets() %>%
  purrr::set_names() %>%
  map(read_excel, path = rosmap_proteomics_results) %>%
  purrr::imap(~mutate(.x, group = .y)) %>% bind_rows()

# results from conditional and standard analysis
res_list <- list()
res_list[['Amyloid*']] <- res %>% filter(adj_p<=pcut & outcome=='abeta_pathology') %>% pull(name) %>% unique()
res_list[['Tangles*']] <- res %>% filter(adj_p<=pcut & outcome=='tau_pathology') %>% pull(name) %>% unique()
res_list[['Amyloid']] <- res %>% filter(adj_p<=pcut & outcome=='sqrt_amyloid') %>% pull(name) %>% unique()
res_list[['Tangles']] <- res %>% filter(adj_p<=pcut & outcome=='tangles') %>% pull(name)%>% unique()
# result list for stacked barplot
tmp <- list()
tmp[['only_st']] <- setdiff(res_list$Tangles, res_list$`Tangles*`) %>% length()
tmp[['only_ct']] <- setdiff(res_list$`Tangles*`, res_list$Tangles) %>% length()
tmp[['both_t']] <- intersect(res_list$Tangles, res_list$`Tangles*`) %>% length()
tmp[['only_sa']] <- setdiff(res_list$Amyloid, res_list$`Amyloid*`) %>% length()
tmp[['only_ca']] <- setdiff(res_list$`Amyloid*`, res_list$Amyloid) %>% length()
tmp[['both_a']] <- intersect(res_list$Amyloid, res_list$`Amyloid*`) %>% length()

# reformat data
tmp2 <- reshape2::melt(tmp)
tmp2$np <- c('t', 't', 't', 'a', 'a', 'a')
tmp2$L1 <- factor(tmp2$L1, levels=c('only_st', 'only_ct', 'both_t', 'only_sa', 'only_ca','both_a'))

# stacked barplot
p1 <- ggplot(tmp2, aes(x=np, y=value, fill=L1, label=value)) +
  geom_bar(stat="identity", position = 'stack') +
  geom_text(size = 3, position = position_stack(vjust = 0.5))+
  xlab("") + ylab("") + theme_classic() +
  theme(text = element_text(size=15))+
  ggtitle ("") +
  scale_fill_manual(values=c('#117A65', '#45B39D', '#73C6B6', '#D4AC0D', '#F7DC6F', '#F9E79F' ), name='Significance')+
  coord_flip(clip = 'off')
pdf("results/Figure3b_proteomics_proteinopathy_barplot.pdf", height = 2, width=6)
plot(p1)
dev.off()


# Figure 4: Replication ----

# ... Mayo ----
# load mayo results
mayo_tcx <- read.xlsx(mayo_results, sheet='AD')
# filter the ones that replicate
mayo_hits <- mayo_tcx %>% filter(replicates=='Yes') %>% 
  # select relevant columns
  select(name, COMP_ID, estimate2, SUB_PATHWAY)
# compare direction with rosmap
plot_mat <- mayo_hits %>% 
  # join rosmap results by comp_id
  left_join(met_stats %>% filter(adj_p<=pcut) %>% select(name, stat_sign, COMP_ID), by='COMP_ID') %>% 
  unique() %>% 
  # compare effect directions
  mutate(comp_w_ref= case_when(
    ((stat_sign > 0 & estimate2) > 0 |  (stat_sign < 0 & estimate2 < 0)) ~ 'same',
    ((stat_sign > 0 & estimate2 < 0) | (stat_sign < 0 & estimate2 > 0)) ~ 'opp',
    TRUE~ NA_character_)) %>% unique()

# format results to be heatmapped
tmp <- plot_mat %>%
  # select relevant columns
  select(name.y, SUB_PATHWAY, comp_w_ref) %>% unique() %>% 
  # effect directions
  mutate(comp_w_ref = as.numeric(factor(comp_w_ref, levels=c('same', 'opp')))) %>% 
  # unknown subpathways
  mutate(SUB_PATHWAY = case_when(is.na(SUB_PATHWAY) ~ 'Unknowns', TRUE~ SUB_PATHWAY)) %>%
  # wide format data frame
  spread(key = SUB_PATHWAY, value= comp_w_ref) %>% 
  mutate(name.y= stringr::str_to_sentence(name.y)) %>% unique()
# to order the data frame that is to be plotted
neworder <- lapply(2:ncol(tmp), FUN=function(i){
  which(!is.na(tmp[,i]))
}) %>% unlist() 

# match the dataframe to the desired order
tmp <- tmp [match(tmp[neworder, 1], tmp$name.y), ]
# extract metabolite names from first column
metabolite_names <- tmp[, 1]
# assign random number 2 to NAs
tmp <- apply(tmp[,-1], 2, FUN=function(x){
  x[which(is.na(x))] <- 2
  x <- as.numeric(as.matrix(x))
  return(x)
})
pdf('results/Figure4a_Mayo_heatmap.pdf', height=9, width=9)
# plotting removing the name of the rows
pheatmap(tmp, cluster_rows = F, 
         cluster_cols = F, labels_row = metabolite_names, 
         angle_col = 90, cellwidth = 10, cellheight = 10, 
         color =c('#2980B9', 'white'),
         gaps_col = (2:ncol(tmp)-1), legend = F)
dev.off()

# ... BLSA ----
# metabolites in the reference: Mahajan et al. 2020 Plos Medicine
# it will be used as reference to check our results
blsa_names <- read.xlsx(blsa_results, sheet="metabolites_measured_mahajan")%>%
  # mapping to the Metabolon names
  left_join(data.frame(rowData(D)[, c('ID', 'name')]), by=c('HMDB'='ID')) %>%
  filter(!is.na(name))

# pathway to metabolite assocaiton from the reference again
blsa_stats <- read.xlsx(blsa_results, sheet="groups_mets")

# joining rosmap results, blsa metabolite names and stats
plot_mat <- met_stats %>%
  # annotating the names
  dplyr::rename(phenotype=Phenotype) %>% 
  left_join(blsa_names, by=c('name'='name')) %>%
  filter(!is.na(metabolite_name)) %>%
  # mapping it using metabolite_name
  right_join(blsa_stats,by='metabolite_name') %>%
  # finding the direction of metabolite in our rosmap analysis
  mutate(direction_w_phenotype=case_when(stat_sign>0 & adj_p<=pcut ~ "positive",
                                         stat_sign<0 & adj_p<=pcut ~ 'negative', TRUE ~ 'nsig')) %>%
  dplyr::rename(direction_w_ad=direction_w_phenotype) %>% 
  # select relevant columns
  select(metabolite_name, phenotype, pathway_name, direction_w_ad, direction_in_mahajan_study) %>% 
  # format data in long format
  reshape2::melt(id=c('metabolite_name', 'direction_w_ad', 'direction_in_mahajan_study')) %>% 
  unique() %>%
  # matching the effect direction in blsa and rosmap study
  mutate(direction_in_mahajan_study = case_when(
    is.na(direction_in_mahajan_study)~ 'nsig', 
    TRUE~direction_in_mahajan_study)) %>% 
  filter(variable=='pathway_name') %>% unique() %>%
  mutate(tmp = factor(direction_w_ad, levels=c('positive','negative', 'nsig'))) %>%
  .[order(.$tmp), ] %>%
  mutate(dup = duplicated(metabolite_name)) %>% filter(dup==FALSE) %>%
  mutate(direction_in_mahajan_study = sub(" ..*", "", direction_in_mahajan_study), 
         comp_w_ref = case_when((direction_w_ad!="nsig" & 
                                   direction_in_mahajan_study=="nsig") ~ "novel", 
                                (direction_w_ad=="negative" & 
                                   direction_in_mahajan_study=="up") ~ "opp", 
                                (direction_w_ad=="positive" & 
                                   direction_in_mahajan_study=="down") ~ "opp", 
                                (direction_w_ad=="nsig" & 
                                   direction_in_mahajan_study!="nsig") ~ "nrep", 
                                (direction_w_ad=="nsig" & 
                                   direction_in_mahajan_study=="nsig") ~ "rem", 
                                TRUE ~ "same" )) %>% unique()
# to be heatmapped
tmp <- plot_mat %>% filter(comp_w_ref!='rem') %>% 
  select(metabolite_name, value, comp_w_ref) %>%
  mutate(comp_w_ref = as.numeric(factor(comp_w_ref, levels=c('nrep', 'same', 'opp', 'novel')))) %>% 
  spread(key = value, value = comp_w_ref)

# new order of metabolites
neworder <- c('Alanine', 'Glutamate', "Betaine", "Choline","Creatine",
              "Methionine", "Methionine sulfoxide", 
              "S-Adenosylhomocysteine (SAH)", "S-Adenosylmethionine (SAM)",
              "GABA", "N-acetlyaspartic acid (NAA)", "Putrescine",
              "Spermidine", "Cysteine", "Glutathione (GSH)", 
              "Arginine", "N-acetylgluatmic acid (NAG)", "Ornithine",
              "Urea")

# data with new order
tmp <- tmp [match(neworder, tmp$metabolite_name), ]
# heatmap
pdf('results/Figure4b_blsa_heatmap.pdf', height=5, width=8)
pheatmap(tmp[, -1], na_col = 'white', cluster_rows = F, 
         cluster_cols = F, labels_row = tmp[, 1], 
         angle_col = 45, cellwidth = 10, cellheight = 10, 
         color =c('#EC7063', '#C1D36A', '#E2C85E', '#A2D9CE'),
         breaks = c(4, 3, 2, 1, 0), legend_breaks = c(4, 3, 2, 1), 
         legend_labels = rev(c('only R', 'B+ & R-', 'B & R', 'only B')), 
         gaps_col = c(1, 2, 3, 4, 5))
dev.off()


# Figures 5 & 6 ----
# These are manually generated diagrams annotated with results from Supplementary Tables 6 & 13


